service: vue-app
runtime: nodejs18
instance_class: F1

handlers:
  - url: /css
    static_dir: dist/css

  - url: /img
    static_dir: dist/img

  - url: /js
    static_dir: dist/js

  # index.html 파일 서빙
  - url: /
    static_files: dist/index.html
    upload: dist/index.html

  # 다른 모든 요청은 index.html로 리디렉션 (SPA)
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html